### ISSUE TITLE
Live server

### ISSUE THREAD

**Issue by Rubylena** [hngi/Pending-Task-Group1#2]
The site cannot be hosted from this repository, because permission has to be given to allow netlify gain access to this repository. 
To solve this, all the files in this repository will be cloned into another repository where it can be hosted from.

**Comment by AyoPips** [comment]
okay please provide the github username of the person handling the server

**Comment by Rubylena** [comment]
Hurshore

**Comment by AyoPips** [comment]
okay he should have access now
